apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-alpha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-alpha
  template:
    metadata:
      labels:
        app: app-alpha
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: app-alpha
        image: busybox
        command: ["sleep", "3600"]
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: host-volume
          mountPath: /host
      volumes:
      - name: host-volume
        emptyDir: {}
